version: '3.8'

services:
  node_app:
    build:
      context: .
      dockerfile: dockerfile
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1.2'
          memory: 600M
        reservations:
          cpus: '1.2'
          memory: 600M
    ports:
      - "3000:3000"
